### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by ghost** [liftedpixel/jammming#1]
It's definitely a good practice to keep your secret API keys out of your Github repos, but if the purpose of the repo is provide a working demo of your work then leaving out the keys defeats the purpose.

You should probably write a README that explains to a potential programmer wanting to use your code that they'll need to include a `.secrets` file (and where to include it) so that they're able to use your code. Always document the specific steps someone will need to follow to make full use of your repo.

<img width="671" alt="screen shot 2017-10-01 at 3 13 28 pm" src="https://user-images.githubusercontent.com/7355203/31058038-293187a0-a6bb-11e7-8a6d-d77789cc8caf.png">

**Comment by liftedpixel** [comment]
In the future, I will leave the keys up longer. I actually had them up at first, then removed them. Before submitting, I should put them back online so pulling down the repo works right away. Since we're done reviewing it for now, I'm leaving the keys out, but added a notice to the readme about it.
